const menu = [
  {
    id: 1,
    title: 'Thai Tea',
    category: 'Tea',
    price: 35,
    img: './images/item-1.jpeg',
    desc: `Authentic Thai tea with a perfect blend of sweetened condensed milk and strong-brewed black tea.`,
  },
  {
    id: 2,
    title: 'Green Tea',
    category: 'Tea',
    price: 35,
    img: './images/item-2.jpeg',
    desc: `Refreshing green tea made from high-quality tea leaves, known for its health benefits and delicate flavor.`,
  },
  {
    id: 3,
    title: 'Lemon Tea ',
    category: 'Tea',
    price: 35,
    img: './images/item-3.jpeg',
    desc: `Classic lemon tea infused with freshly squeezed lemon juice, offering a tangy and invigorating taste.`,
  },
  {
    id: 4,
    title: 'Taiwan Tea ',
    category: 'Tea',
    price: 35,
    img: './images/item-4.jpeg',
    desc: `Taiwanese-style tea known for its rich aroma and distinctive flavor, a favorite among tea enthusiasts.`,
  },
  {
    id: 5,
    title: 'Cappuccino',
    category: 'Coffee',
    price: 45,
    img: './images/item-5.jpg',
    desc: `Classic cappuccino crafted with freshly ground espresso, steamed milk, and a frothy milk foam, perfect for coffee lovers.`,
  },
  {
    id: 6,
    title: 'Americano',
    category: 'Coffee',
    price: 45,
    img: './images/item-6.jpeg',
    desc: `Strong and bold Americano made by diluting espresso with hot water, providing a rich and intense coffee experience.`,
  },
  {
    id: 7,
    title: 'Latte  ',
    category: 'Coffee',
    price: 45,
    img: './images/item-7.jpg',
    desc: `Creamy latte topped with a velvety layer of milk foam, offering a smooth and indulgent coffee treat.`,
  },
  {
    id: 8,
    title: 'Coconut Milk Shake',
    category: 'Juice',
    price: 30,
    img: './images/item-8.jpeg',
    desc: `Refreshing coconut milk shake blended with fresh coconut water and creamy coconut milk, perfect for a tropical escape.`,
  },
  {
    id: 9,
    title: 'Apple Soda',
    category: 'Juice',
    price: 30,
    img: './images/item-9.jpeg',
    desc: `Sparkling apple soda made from crisp and juicy apples, providing a crisp and refreshing beverage option.`,
  },
  {
    id: 10,
    title: 'Strawberry Soda',
    category: 'Juice',
    price: 30,
    img: './images/item-10.jpeg',
    desc: `Bubbly strawberry soda bursting with sweet and tangy flavors, ideal for quenching your thirst on a hot day.`,
  },
];
export default menu;
